import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const check = process.argv.includes("--check");
const REPO = join(here, "..");
const scriptcRoot = resolveScriptc();

function resolveScriptc() {
  const env = process.env.SCRIPTC_ROOT;
  const candidates = env ? [env] : [join(REPO, "..", "..", "scriptc"), join(REPO, "..", "scriptc")];
  for (const c of candidates) {
    if (existsSync(join(c, "package.json"))) return c;
  }
  console.error(
    "cannot find the scriptc checkout" +
      (env ? ` at SCRIPTC_ROOT=${env}` : "") +
      " — set SCRIPTC_ROOT to it",
  );
  process.exit(1);
}

const react = JSON.parse(readFileSync(join(here, "react.surface.json"), "utf8"));

// Everything claimed as implemented must actually be exported.
const exported = new Set(
  [...readFileSync(join(here, "react.ts"), "utf8").matchAll(/^export (?:function|const|interface|type) (\w+)/gm)]
    .map((m) => m[1]),
);
const lying = [...react.hooks, ...react.api]
  .filter((e) => e.status === "yes" && !exported.has(e.name))
  .map((e) => e.name);
if (lying.length > 0) {
  console.error(`compat: claimed but not exported by compat/react.ts: ${lying.join(", ")}`);
  process.exit(1);
}

const mark = (s) => (s === "yes" ? "yes" : s === "different" ? "different" : "no");
const rows = (list) =>
  list.map((e) => `| \`${e.name}\` | ${mark(e.status)} | ${e.note ?? ""} |`).join("\n");
const table = (list) => `| | supported | |\n|---|---|---|\n${rows(list)}`;
const count = (list, s) => list.filter((e) => e.status === s).length;

// Node support is projected from scriptc's own manifest, not restated here.
const manifest = JSON.parse(
  readFileSync(join(scriptcRoot, "packages/compiler/surface-manifest.json"), "utf8"),
);
const nodeEntries = manifest.entries.filter((e) => e.id.startsWith("node-builtin."));
const byModule = new Map();
for (const e of nodeEntries) {
  const mod = e.name.split(".")[0];
  if (!byModule.has(mod)) byModule.set(mod, { ok: [], missing: [] });
  const bucket = byModule.get(mod);
  if (e.status === "static") bucket.ok.push(e);
  else bucket.missing.push(e);
}
const modRows = [...byModule.entries()]
  .filter(([, v]) => v.ok.length + v.missing.length > 1)
  .sort((a, b) => b[1].missing.length - a[1].missing.length || a[0].localeCompare(b[0]))
  .map(([mod, v]) => `| \`${mod}\` | ${v.ok.length} | ${v.missing.length} |`)
  .join("\n");

const missingNode = nodeEntries
  .filter((e) => e.status !== "static")
  .sort((a, b) => a.name.localeCompare(b.name))
  .map((e) => `| \`${e.name}\` | ${e.code ?? ""} | ${shorten(e.note)} |`)
  .join("\n");

const nodeOk = nodeEntries.filter((e) => e.status === "static").length;

function shorten(note) {
  const first = (note ?? "").split("\n")[0];
  const cut = first.split(" \u2014 ")[0];
  return cut.length > 110 ? cut.slice(0, 107) + "..." : cut;
}

const body = `# Compatibility

What compiles. Generated by \`compat/generate.mjs\` from \`compat/react.surface.json\`
and scriptc's \`surface-manifest.json\`; run \`--check\` to fail on drift.

There is no React runtime and no Node runtime in a built binary. These are
source-level surfaces: your code is compiled against implementations in
\`compat/\` and scriptc's lowerings. Anything below marked unsupported is a
compile error, not a runtime failure.

## React hooks

${count(react.hooks, "yes")} of ${react.hooks.length} implemented.

${table(react.hooks)}

## React top-level API

${count(react.api, "yes")} of ${react.api.length} implemented.

${table(react.api)}

## JSX

${count(react.jsx, "yes")} of ${react.jsx.length} supported.

${table(react.jsx)}

## Node builtins

${nodeOk} of ${nodeEntries.length} members lower statically, projected from
scriptc's manifest at compiler ${manifest.compilerVersion}.

| module | lowers | missing |
|---|---|---|
${modRows}

### Missing node members

| member | code | why |
|---|---|---|
${missingNode}
`;

const path = join(here, "COMPATIBILITY.md");
const prev = (() => { try { return readFileSync(path, "utf8"); } catch { return ""; } })();
if (body === prev) {
  console.log("compat: up to date");
} else if (check) {
  console.error("compat: COMPATIBILITY.md out of date — run: node compat/generate.mjs");
  process.exit(1);
} else {
  writeFileSync(path, body);
  console.log(`compat: wrote COMPATIBILITY.md (${react.hooks.length + react.api.length + react.jsx.length} react rows, ${nodeEntries.length} node members)`);
}
